### ISSUE TITLE
can add option if change something in workflow?

### ISSUE THREAD

**Issue by 7eyen** [SamKirkland/FTP-Deploy-Action-Typescript#2]
Hello
For some reason, I need to replace the file contents in the repository with confidential information in the workflow, but committing these changes in the workflow will cause `.git-ftp.log` to point to an unknown commit id.

> Some ideas 

```sh
#do repalce in a.txt use github secrets here
git add .
git commit -am 'commit by ci'
git ftp push
if [ ! -n "$option" ]; then
  git reset --hard HEAD~
  git ftp catchup
if
````
❤️

**Comment by SamKirkland** [comment]
I've never had the need to commit during a github action.
Would it be possible to avoid a commit in the action by using [git-ftp syncing untracked files option](https://github.com/git-ftp/git-ftp/blob/master/man/git-ftp.1.md#syncing-untracked-files)? This way you can modify the file in the action any always upload it without making the commit :)

**Comment by 7eyen** [comment]
The `.git-ftp-include` only working on remotely untracked.But i need to modi some tracked file. I changed some steps in docker to solve my problem.

```sh
if [[ -n $(git status -s) ]]
then
    git log --oneline
    git add .
    git commit -am 'commit by ci' -v
    git log --oneline
else
    git ftp push --auto-init $DEFAULT_ARGS
    exit
fi

git ftp push --auto-init $DEFAULT_ARGS

git reset --hard HEAD~
git ftp catchup $DEFAULT_ARGS
```

**Comment by SamKirkland** [comment]
Hey @7eyen I've merged this branch and [officially release it as V3](SamKirkland/FTP-Deploy-Action/releases)

Future changes/support will be done under the [FTP-Deploy-Action](/SamKirkland/FTP-Deploy-Action) branch. Please migrate.
