### ISSUE TITLE
Char appearing on server name

### ISSUE THREAD

**Issue by tiagoaguiar31** [SamKirkland/FTP-Deploy-Action-Typescript#4]
Hi Sam,

My actions were working fine until Friday, but for some reason it's not anymore. I did a little debug and find out that a few chars are being inserted inside the ftps domain server.
ftps://**%27**domain-server%5c%username**%27**:***user (...)

Any idea how can I solve this?

**Comment by carlos-sergio-carvalho** [comment]
Same issue here , looks like we have a  ' in the command

**Comment by SamKirkland** [comment]
Sorry guys. I didn't realize people we actively using this action (unfortunately github doesn't allow me to see a dependency count).

I've published a fix.

Just so you two are aware, my long-term plan is to merge this rewrite with [FTP-Deploy-Action](https://github.com/SamKirkland/FTP-Deploy-Action) under version 3 and remove this project.

**Comment by carlos-sergio-carvalho** [comment]
tks a lot man!

**Comment by SamKirkland** [comment]
Hey @tiagoaguiar31 and @carlos-sergio-carvalho,

I've merged this branch and [officially release it as V3](SamKirkland/FTP-Deploy-Action/releases)

Future changes/support will be done under the [FTP-Deploy-Action](/SamKirkland/FTP-Deploy-Action) branch. Please migrate.

**Comment by tiagoaguiar31** [comment]
Thanks for the help Sam!
